use supply_chain;


-- questions--
-- 1. Read the data from all the tables

select * from customer;
select * from orderitem;
select * from orders;
select * from product;
select * from supplier;

-- 2nd question --
-- Find the country-wise count of customers
select country, count(*) as customer_count
from customer
group by country
order by customer_count desc;

-- 3---
-- Display the products that are not discontinued

select * from product where isdiscontinued =0;

-- 4 ---
-- Display the list of companies along with the product name that they are supplying

select c.country, b.productname
from supplier c
inner join product b
on c.id= b.id;

-- 5  Display customer information about who stays in 'Mexico' --
select * from customer
where country ="Mexico";

-- 6 Display the costliest item that is ordered by the customer  --
-- SELECT c.firstname, max(p.unitprice) as maxprice
-- from customer c 
-- join product p
-- on c.id = p.id
-- group by firstname
-- order by maxprice desc;

SELECT c.id AS customer_id, p.productname, p.unitprice 
FROM customer c 
JOIN orders o ON c.id = o.customerid
JOIN orderitem oi ON o.id = oi.orderid
JOIN product p ON p.id = oi.productid
WHERE (c.id, p.unitprice) IN (
    SELECT c.id, MAX(p.unitprice) 
    FROM product p
    JOIN orderitem oi ON oi.productid = p.id
    JOIN orders o ON o.id = oi.orderid
    JOIN customer c ON o.customerid = c.id
    GROUP BY c.id
);

-- question 7 Top Suppliers: Find the Supplier ID that provides the highest number of products.
with max_p as(select s.id, count(p.id) as cnt
from supplier s
join product p
on p.supplierid=s.id
group by s.id
)
select * from max_p
where cnt in(select max(cnt) from max_p);

-- question 8 
-- Order Trends: Display the count of orders placed each month and year.
select year(OrderDate) as year, month(OrderDate) as month, count(id) as order_count
from orders 
group by year(OrderDate),month(OrderDate)
order by year asc, month asc;

-- question 9
-- Supplier Concentration: Which country has the maximum number of suppliers?
with country_count as (
select country,count(id) over(partition by country) as cnt
from supplier)
select * from country_count
where cnt=(select max(cnt) from country_count);

-- question 10
-- Inactive Customers: Identify customers who have never placed an order

SELECT * FROM customer
WHERE id NOT IN (SELECT customerid FROM orders);

-- 2nd method
select *
from customer c
left join orders O on c.id= O.customerid
where o.id is null;

-- Section B: Level 2 (Intermediate Queries)
-- question 1 Product Demand: Rank Product IDs and Names based on the total quantity ordered by customers.
select p.id as product_id, p.productname, sum(oi.quantity) as total_quantity
from orderitem oi
join product p on p.id=oi.productid
group by p.id,p.productname
order by total_quantity desc;

-- question 2 Annual Performance: Display the total number of orders delivered each year

select year(OrderDate) as year, count(id) as total_order
from orders
group by year(OrderDate);


-- question 3 Revenue Analysis: Calculate the total revenue generated each year.

select year(OrderDate) as year, sum(totalamount) as total_revenue
from orders
group by year(OrderDate);

-- question 4 Display the customer details whose order amount is maximum including his past orders

select c.*, sum(totalamount) as total_amount
from customer c
join orders o on o.customerid = c.id
group by c.id
order by sum(totalamount) desc
limit 1;

-- question 5 
-- Display the total amount ordered by each customer from high to low

select c.*, sum(totalamount) as total_amount
from customer c
join orders o on o.customerid = c.id
group by c.id
order by sum(totalamount) desc;

-- question 6 
--  List the current and previous order dates for each customer

-- SELECT c.id AS customerid, c.firstname, o.orderdate
-- FROM customer c 
-- JOIN orders o ON o.customerid = c.id
-- ORDER BY customerid, orderdate;

SELECT 
    customerid,
    orderdate AS current_order_date,
    LAG(orderdate) OVER (PARTITION BY customerid ORDER BY orderdate) AS previous_order_date
FROM orders;

-- question 7
-- Identify the top 3 suppliers based on the total revenue generated by their products.

select s.id as supplierid, s.contactname, sum(oi.quantity* oi.unitprice) as total_revenue
from supplier s
join product p on p.supplierid=s.id
join orderitem oi on oi.productid=p.id
join orders o on o.id= oi.orderid
group by s.id,s.contactname
order by total_revenue desc
limit 3;


-- question 8
--  Display the latest order date of all the customers with customer details

select c.* , max(orderdate) as latest_order_date
from customer c 
join orders o on o.customerid = c.id
group by c.id;

-- question 9
-- For every order, display the Order ID, Product Name, and Supplier Name.


select oi.orderid, p.productname , s.contactname as supliername
from supplier s
join product p on p.supplierid = s.id
join orderitem oi on oi.productid = p.id
join orders o on o.id= oi.orderid;


-- Section C: Level 3 (Advanced Queries)
-- Fetch the customer details who ordered more than 10 products in a single order


with product_ordered as (select distinct c.*, count(o.id) over (partition by c.id) as count
from customer c
join orders o on o.customerid=c.id)

select * from product_ordered
where count>10
order by count desc; 

-- question 2
-- Display all the product details with the ordered quantity size as 1

select p.* from product p
join orderitem oi on oi.productid=p.id
where quantity =1;

-- question 3
-- Display the companies that supply products whose cost is above 100

select s.*
from supplier s
join product p on p.supplierid=s.id
join orderitem oi on oi.productid= p.id
where oi.unitprice>100;

-- question 4 
-- Display the customer list who belongs to the same city and country arranged country-wise

select c1.id,c1.firstname,c2.firstname,c1.city,c1.country 
from customer c1
join customer c2 on (c1.city,c1.country)=(c2.city,c2.country)
where c1.id<>c2.id
order by c1.country;

-- Section D: Level 4 (Expert Queries)
-- Savings Analysis: The company offers discounts. Calculate the total amount saved in each order (Actual Price - Selling Price) and rank orders by total savings.


select oi.orderid, sum((p.unitprice- oi.unitprice)*oi.quantity) as total_saving
from product p 
join orderitem oi on oi.productid =p.id
group by oi.orderid
order by total_saving desc;

-- question 2 
-- Market Research: Help a new supplier, Mr. Kavin, by identifying:
-- a. A list of high-demand products he should consider supplying.
-- b. A list of his potential competitors for those products.

-- a A list of high-demand products he should consider supplying.
select p.productname, sum(oi.quantity) as total_demand
from product p 
join orderitem oi on oi.productid=p.id
group by p.productname
order by total_demand desc;

-- b  A list of his potential competitors for those products.

select distinct s.contactname ,p.productname
from orderitem oi
join product p on p.id= oi.productid
join supplier s on p.supplierid = s.id;
